### ISSUE TITLE
"loginResult": null when i run createUser mutation 

### ISSUE THREAD

**Issue by ibelarouci** [pradel/accounts-js-server-tutorial#1]
thanks for the nice tuto, so
why loginResult is null when i create a user by createUser Mutation?
 
![image](https://user-images.githubusercontent.com/8080006/111226403-5d09ef00-85e1-11eb-888b-59724c25cfa7.png)
the user is successfully created under mongodb 
![image](https://user-images.githubusercontent.com/8080006/111227507-f38ae000-85e2-11eb-84bc-a56d24b4ebe7.png)

for your info  the npm update --force generate this  
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @accounts/password@0.31.1
npm WARN node_modules/@accounts/password
npm WARN   @accounts/password@"^0.31.1" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @accounts/password@"^0.30.0" from @accounts/graphql-api@0.31.1
npm WARN node_modules/@accounts/graphql-api
npm WARN   @accounts/graphql-api@"^0.31.1" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @accounts/server@0.31.1
npm WARN node_modules/@accounts/server
npm WARN   @accounts/server@"^0.31.1" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @accounts/server@"^0.30.0" from @accounts/password@0.31.1
npm WARN node_modules/@accounts/password
npm WARN   @accounts/password@"^0.31.1" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @accounts/server@0.31.1
npm WARN node_modules/@accounts/server
npm WARN   @accounts/server@"^0.31.1" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @accounts/server@"^0.30.0" from @accounts/graphql-api@0.31.1
npm WARN node_modules/@accounts/graphql-api
npm WARN   @accounts/graphql-api@"^0.31.1" from the root project
npm WARN deprecated @graphql-toolkit/common@0.10.6: GraphQL Toolkit is deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-toolkit for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.

**Comment by pradel** [comment]
User is null to disable user enumeration. You can get the user directly if you set the `ambiguousErrorMessages` server option to false.
https://www.accountsjs.com/docs/api/server/interfaces/accountsserveroptions/#optional-ambiguouserrormessages

**Comment by ibelarouci** [comment]
thank you, i love it :+1:
